version: '3.8'

services: 
  app:
    image: webdevops/php-apache:7.4
    container_name: hashpik_app
    volumes:
      - /opt/lampp/htdocs/Hashpik:/app
    ports:
      - "8081:80"
    depends_on:
      - db
    restart: always
  db:
    image: mysql:8.0
    container_name: hashpik_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hashpik
      MYSQL_USER: hashpik_user
      MYSQL_PASSWORD: hashpik_pass
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data: